services:
  backend:
    build: ./backend
    ports:
      - "8080:8000"
    env_file: ".env"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
        - action: rebuild
          path: package.json
    command: "uvicorn graymatter.main:app --host 0.0.0.0 --port 8000 --reload"
